import type { Locale } from "./config";

const copy = {
  en: { privacyTitle: "Privacy policy", privacy: ["Nancy's Castalla uses customer details only to manage accounts, answer enquiries, process orders and arrange collection or delivery.", "Account authentication is provided by Supabase. Order and customer records are stored securely and are not sold to third parties. Necessary providers process data only for authentication, hosting and transactional email.", "You may request access, correction or deletion of your personal data using the account email address below.", "Only technically necessary account storage is used. This policy will be expanded before analytics, advertising or online payments are activated."], termsTitle: "Terms and ordering", terms: ["Orders during the pre-order phase are requests until Nancy's Castalla confirms availability, the final amount and collection or delivery arrangements.", "Prices include applicable IVA. Availability may change before confirmation. Delivery depends on route and timing and may require the configured minimum order and delivery fee.", "Payment is arranged after confirmation by Bizum or bank transfer. Perishable and frozen products must be collected or received at the agreed time.", "Questions about an order can be sent to the order email address below."] },
  nl: { privacyTitle: "Privacybeleid", privacy: ["Nancy's Castalla gebruikt klantgegevens uitsluitend voor accounts, vragen, bestellingen en het regelen van afhalen of bezorgen.", "Supabase verzorgt de accountbeveiliging. Bestel- en klantgegevens worden veilig opgeslagen, niet verkocht en alleen door noodzakelijke dienstverleners verwerkt.", "Je kunt via onderstaand accountadres inzage, correctie of verwijdering van persoonsgegevens aanvragen.", "Alleen technisch noodzakelijke accountopslag wordt gebruikt. Dit beleid wordt uitgebreid voordat analytics, advertenties of online betalingen actief worden."], termsTitle: "Voorwaarden en bestellen", terms: ["Bestellingen in de pre-orderfase zijn aanvragen totdat Nancy's Castalla beschikbaarheid, eindbedrag en afhaal- of bezorgafspraken bevestigt.", "Prijzen zijn inclusief toepasselijke IVA. Beschikbaarheid kan vóór bevestiging wijzigen. Voor bezorging kunnen het ingestelde minimumbedrag en bezorgkosten gelden.", "Betaling wordt na bevestiging geregeld via Bizum of bankoverschrijving. Verse en diepvriesproducten moeten op het afgesproken moment worden ontvangen.", "Vragen over een bestelling kunnen naar onderstaand besteladres worden gestuurd."] },
  de: { privacyTitle: "Datenschutz", privacy: ["Nancy's Castalla verwendet Kundendaten nur für Konten, Anfragen, Bestellungen sowie Abholung oder Lieferung.", "Supabase stellt die Kontoauthentifizierung bereit. Bestell- und Kundendaten werden sicher gespeichert, nicht verkauft und nur von notwendigen Dienstleistern verarbeitet.", "Über die unten genannte Konto-E-Mail können Sie Auskunft, Berichtigung oder Löschung beantragen.", "Es wird nur technisch notwendiger Kontospeicher verwendet. Vor Analytics, Werbung oder Online-Zahlungen wird diese Richtlinie erweitert."], termsTitle: "Bedingungen und Bestellung", terms: ["Bestellungen in der Vorbestellphase sind Anfragen, bis Nancy's Castalla Verfügbarkeit, Endbetrag und Abholung oder Lieferung bestätigt.", "Preise enthalten die geltende IVA. Die Verfügbarkeit kann sich vor Bestätigung ändern. Für Lieferungen können Mindestbestellwert und Gebühr gelten.", "Die Zahlung wird nach Bestätigung per Bizum, Überweisung oder bar vereinbart. Kühl- und Tiefkühlware muss zum vereinbarten Zeitpunkt übernommen werden.", "Fragen zu Bestellungen können an die unten genannte Bestelladresse gesendet werden."] },
  es: { privacyTitle: "Política de privacidad", privacy: ["Nancy's Castalla utiliza los datos del cliente solo para cuentas, consultas, pedidos y para organizar la recogida o entrega.", "Supabase proporciona la autenticación. Los datos se guardan de forma segura, no se venden y solo los tratan proveedores necesarios.", "Puedes solicitar acceso, corrección o eliminación de tus datos mediante el correo de cuentas indicado abajo.", "Solo se utiliza almacenamiento técnicamente necesario. Esta política se ampliará antes de activar analítica, publicidad o pagos online."], termsTitle: "Condiciones y pedidos", terms: ["Los pedidos durante la fase de prepedido son solicitudes hasta que Nancy's Castalla confirme disponibilidad, importe final y recogida o entrega.", "Los precios incluyen el IVA aplicable. La disponibilidad puede cambiar antes de la confirmación. La entrega puede requerir el pedido mínimo y la tarifa configurados.", "El pago se acuerda tras la confirmación mediante Bizum o transferencia bancaria. Los productos frescos y congelados deben recibirse a la hora acordada.", "Las consultas sobre pedidos pueden enviarse al correo de pedidos indicado abajo."] },
  sv: { privacyTitle: "Integritetspolicy", privacy: ["Nancy's Castalla använder kunduppgifter endast för konton, frågor, beställningar samt avhämtning eller leverans.", "Supabase tillhandahåller autentisering. Uppgifter lagras säkert, säljs inte och behandlas endast av nödvändiga leverantörer.", "Du kan begära tillgång, rättelse eller radering via kontots e-postadress nedan.", "Endast tekniskt nödvändig kontolagring används. Policyn utökas innan analys, annonsering eller onlinebetalning aktiveras."], termsTitle: "Villkor och beställning", terms: ["Beställningar under förbeställningsfasen är förfrågningar tills Nancy's Castalla bekräftar tillgänglighet, slutbelopp och avhämtning eller leverans.", "Priser inkluderar tillämplig IVA. Tillgänglighet kan ändras före bekräftelse. Leverans kan kräva angivet minimibelopp och avgift.", "Betalning ordnas efter bekräftelse via Bizum eller banköverföring. Kylda och frysta produkter måste tas emot vid avtalad tid.", "Frågor om beställningar kan skickas till beställningsadressen nedan."] },
} as const;

export function getLegalCopy(locale: Locale) { return copy[locale]; }
