alter table products add column if not exists uuid uuid not null default gen_random_uuid();
alter table products add column if not exists sku text;
alter table products add column if not exists ean text not null default '';
alter table products add column if not exists stock_quantity numeric not null default 0;
alter table products add column if not exists minimum_stock numeric not null default 0;
alter table products add column if not exists track_inventory boolean not null default false;
alter table products add column if not exists weight text not null default '';
alter table products add column if not exists images jsonb not null default '[]'::jsonb;
alter table products add column if not exists is_new boolean not null default false;

update products set sku = id where sku is null or sku = '';
create unique index if not exists products_uuid_key on products(uuid);
create unique index if not exists products_sku_key on products(sku);
create index if not exists products_ean_idx on products(ean) where ean <> '';
create index if not exists products_low_stock_idx on products(track_inventory, stock_quantity, minimum_stock);

alter table orders add column if not exists uuid uuid not null default gen_random_uuid();
alter table orders add column if not exists order_number bigint generated by default as identity;
alter table orders add column if not exists customer_id uuid;
alter table orders add column if not exists payment_status text not null default 'pending';
alter table orders add column if not exists delivery_method text not null default '';
alter table orders add column if not exists updated_at timestamptz not null default now();
update orders set delivery_method = fulfillment where delivery_method = '';
create unique index if not exists orders_uuid_key on orders(uuid);
create unique index if not exists orders_order_number_key on orders(order_number);
create index if not exists orders_status_idx on orders(status, created_at desc);

create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  email text not null unique,
  phone text not null default '',
  address text not null default '',
  language text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'orders_customer_id_fkey') then
    alter table orders
      add constraint orders_customer_id_fkey
      foreign key (customer_id) references customers(id) on delete set null
      not valid;
  end if;
end $$;

create table if not exists suppliers (
  id uuid primary key default gen_random_uuid(),
  code text unique,
  name text not null unique,
  email text not null default '',
  phone text not null default '',
  address text not null default '',
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into suppliers (name)
select distinct supplier from products where supplier <> ''
on conflict (name) do nothing;

create table if not exists inventory_movements (
  id uuid primary key default gen_random_uuid(),
  product_id text references products(id) on delete set null,
  order_id text references orders(id) on delete set null,
  movement_type text not null,
  quantity numeric not null,
  reference text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists inventory_movements_product_idx on inventory_movements(product_id, created_at desc);

create table if not exists purchase_orders (
  id uuid primary key default gen_random_uuid(),
  purchase_number bigint generated by default as identity unique,
  supplier_id uuid references suppliers(id) on delete set null,
  status text not null default 'draft',
  total_ex_vat numeric not null default 0,
  total_vat numeric not null default 0,
  total_incl_vat numeric not null default 0,
  expected_at timestamptz,
  received_at timestamptz,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number bigint generated by default as identity unique,
  order_id text references orders(id) on delete set null,
  customer_id uuid references customers(id) on delete set null,
  status text not null default 'draft',
  total_ex_vat numeric not null default 0,
  total_vat numeric not null default 0,
  total_incl_vat numeric not null default 0,
  issued_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists integration_settings (
  id uuid primary key default gen_random_uuid(),
  provider text not null unique,
  enabled boolean not null default false,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table customers enable row level security;
alter table suppliers enable row level security;
alter table inventory_movements enable row level security;
alter table purchase_orders enable row level security;
alter table invoices enable row level security;
alter table integration_settings enable row level security;

create or replace function create_order_with_inventory(
  p_order_id text,
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_fulfillment text,
  p_notes text,
  p_total numeric,
  p_lines jsonb
)
returns table(order_number bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id uuid;
  v_order_number bigint;
  v_line jsonb;
  v_stock_delta numeric;
begin
  insert into customers (name, email, phone)
  values (p_customer_name, lower(p_customer_email), coalesce(p_customer_phone, ''))
  on conflict (email) do update
    set name = excluded.name,
        phone = case when excluded.phone <> '' then excluded.phone else customers.phone end,
        updated_at = now()
  returning id into v_customer_id;

  insert into orders (
    id, customer_id, customer_name, customer_email, customer_phone,
    fulfillment, delivery_method, notes, total, status, payment_status
  ) values (
    p_order_id, v_customer_id, p_customer_name, lower(p_customer_email), coalesce(p_customer_phone, ''),
    p_fulfillment, p_fulfillment, coalesce(p_notes, ''), p_total, 'new', 'pending'
  ) returning orders.order_number into v_order_number;

  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    insert into order_items (
      order_id, product_id, product_name, quantity, unit,
      package_label, package_quantity, sale_price_incl_vat
    ) values (
      p_order_id,
      v_line->>'productId',
      v_line->>'name',
      (v_line->>'quantity')::integer,
      v_line->>'unit',
      coalesce(v_line->>'packageLabel', ''),
      coalesce((v_line->>'packageQuantity')::numeric, 1),
      (v_line->>'salePriceInclVat')::numeric
    );

    v_stock_delta := (v_line->>'quantity')::numeric * coalesce((v_line->>'packageQuantity')::numeric, 1);
    update products
      set stock_quantity = greatest(stock_quantity - v_stock_delta, 0)
      where id = v_line->>'productId' and track_inventory = true;

    if found then
      insert into inventory_movements (product_id, order_id, movement_type, quantity, reference)
      values (v_line->>'productId', p_order_id, 'sale', -v_stock_delta, 'Order ' || v_order_number);
    end if;
  end loop;

  return query select v_order_number;
end;
$$;
