alter table invoices add column if not exists customer_name text not null default '';
alter table invoices add column if not exists customer_email text not null default '';
alter table invoices add column if not exists customer_phone text not null default '';
alter table invoices add column if not exists billing_address text not null default '';
alter table invoices add column if not exists customer_language text not null default 'en';
alter table invoices add column if not exists order_number bigint;
alter table invoices add column if not exists payment_method text;
alter table invoices add column if not exists email_sent_at timestamptz;
alter table invoices add column if not exists updated_at timestamptz not null default now();

create unique index if not exists invoices_one_per_order_idx on invoices(order_id) where order_id is not null;

create table if not exists invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id uuid not null references invoices(id) on delete cascade,
  product_id text,
  product_name text not null,
  package_label text not null default '',
  quantity numeric not null,
  unit_price_incl_vat numeric not null,
  vat_rate numeric not null default 0,
  line_total_ex_vat numeric not null,
  line_vat numeric not null,
  line_total_incl_vat numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists invoice_items_invoice_idx on invoice_items(invoice_id);
alter table invoice_items enable row level security;

create or replace function create_invoice_from_order(p_order_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order orders%rowtype;
  v_customer customers%rowtype;
  v_invoice_id uuid;
  v_address text;
begin
  select * into v_order from orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if v_order.status not in ('confirmed', 'ready_for_collection', 'delivered') and v_order.payment_status <> 'paid' then
    raise exception 'invoice_not_allowed';
  end if;
  if not exists (select 1 from order_items where order_id = p_order_id) then
    raise exception 'order_has_no_items';
  end if;

  select * into v_customer from customers where id = v_order.customer_id;
  v_address := coalesce(nullif(v_customer.address, ''), substring(v_order.notes from '(?im)^(?:Address|Adres|Adresse|Dirección|Adress):\s*(.+)$'), '');

  insert into invoices (
    order_id, customer_id, status, total_ex_vat, total_vat, total_incl_vat, issued_at,
    customer_name, customer_email, customer_phone, billing_address, customer_language,
    order_number, payment_method
  ) values (
    v_order.id, v_order.customer_id, 'issued', v_order.subtotal_ex_vat, v_order.vat_total, v_order.total, now(),
    v_order.customer_name, v_order.customer_email, v_order.customer_phone, v_address,
    coalesce(nullif(v_customer.language, ''), 'en'), v_order.order_number, null
  )
  on conflict (order_id) where order_id is not null do nothing
  returning id into v_invoice_id;

  if v_invoice_id is null then
    select id into v_invoice_id from invoices where order_id = p_order_id;
    return v_invoice_id;
  end if;

  insert into invoice_items (
    invoice_id, product_id, product_name, package_label, quantity, unit_price_incl_vat,
    vat_rate, line_total_ex_vat, line_vat, line_total_incl_vat
  )
  select v_invoice_id, product_id, product_name, coalesce(nullif(package_label, ''), unit), quantity,
    sale_price_incl_vat, vat_rate, line_total_ex_vat,
    line_total_incl_vat - line_total_ex_vat, line_total_incl_vat
  from order_items where order_id = p_order_id order by id;

  return v_invoice_id;
end;
$$;

revoke all on function create_invoice_from_order(text) from public, anon, authenticated;
grant execute on function create_invoice_from_order(text) to service_role;
